export const queryKeys = {
  products: (params = {}) => ['products', params],
  product: (id) => ['product', id],
  categories: ['categories'],
  brands: ['brands'],
  me: ['me'],
  cart: ['cart'],
  addresses: ['addresses'],
  shippingPrices: ['shipping-prices'],
  orders: (params = {}) => ['orders', params],
  order: (id) => ['order', id],
  adminStats: ['admin', 'stats'],
  adminProducts: (params = {}) => ['admin', 'products', params],
  adminCategories: ['admin', 'categories'],
  adminUsers: (params = {}) => ['admin', 'users', params],
};
